# 本章导学

在大多数现代语言中, 都拥有一套完善的错误处理机制(error handing). 在一些典型的面向对象语言, 例如 Java 和 Python 中, 错误使用 try…catch 语法进行处理, 但这种机制却存在显著的问题.

我们此处借用 Golang 的说法, Golang 认为程序中会出现两种错误：错误和异常. 异常是开发者无法预料且超出自己能力范围的错误, 例如访问数组越界, 一旦出现异常, 这说明程序代码本身的逻辑就是有问题的. 还有一种是错误, 典型的比如建立 TCP 连接失败, 很显然开发者应该能预料到这种问题并且有能力去解决, 例如在代码中加入重试功能. 错误是正常的程序逻辑的一部分.

像 Java 和 Python 的问题就是没有区分这两种错误, 它们统一使用 Exception(异常) 来表示它们, 这使得程序的控制流显得特别混乱.

Rust 的错误处理机制与 Golang 特别相似, 它将错误分为可恢复错误和不可恢复错误. 如果遇到不可恢复错误程序将奔溃退出, 而可恢复错误则就像一个正常的函数返回值一样. 不要误认为程序奔溃是坏事, 事实上提早崩溃(early crash)是一种被广泛使用的设计方法论.

Rust 有两种语法来实现可恢复错误和不可恢复错误, 它们分别是 `Result<T, E>` 和 `panic!`. 前者是一个泛型枚举, 后者则是一个宏.
